# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ReportsScreenResearcher.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(477, 476)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.cur_report_display_table = QtWidgets.QTableWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cur_report_display_table.sizePolicy().hasHeightForWidth())
        self.cur_report_display_table.setSizePolicy(sizePolicy)
        self.cur_report_display_table.setLineWidth(1)
        self.cur_report_display_table.setObjectName("cur_report_display_table")
        self.cur_report_display_table.setColumnCount(1)
        self.cur_report_display_table.setRowCount(11)
        item = QtWidgets.QTableWidgetItem()
        self.cur_report_display_table.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.cur_report_display_table.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.cur_report_display_table.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.cur_report_display_table.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.cur_report_display_table.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.cur_report_display_table.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.cur_report_display_table.setVerticalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.cur_report_display_table.setVerticalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.cur_report_display_table.setVerticalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.cur_report_display_table.setVerticalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.cur_report_display_table.setVerticalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        self.cur_report_display_table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.cur_report_display_table.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.cur_report_display_table.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.cur_report_display_table.setItem(2, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.cur_report_display_table.setItem(3, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.cur_report_display_table.setItem(4, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.cur_report_display_table.setItem(5, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.cur_report_display_table.setItem(6, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.cur_report_display_table.setItem(7, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.cur_report_display_table.setItem(8, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.cur_report_display_table.setItem(9, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.cur_report_display_table.setItem(10, 0, item)
        self.cur_report_display_table.horizontalHeader().setDefaultSectionSize(300)
        self.verticalLayout_2.addWidget(self.cur_report_display_table)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Report screen:"))
        item = self.cur_report_display_table.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "beta1,0"))
        item = self.cur_report_display_table.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "beta2,0"))
        item = self.cur_report_display_table.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", "beta3,0"))
        item = self.cur_report_display_table.verticalHeaderItem(3)
        item.setText(_translate("MainWindow", "beta4,0"))
        item = self.cur_report_display_table.verticalHeaderItem(4)
        item.setText(_translate("MainWindow", "beta5,0"))
        item = self.cur_report_display_table.verticalHeaderItem(5)
        item.setText(_translate("MainWindow", "amount of sleep"))
        item = self.cur_report_display_table.verticalHeaderItem(6)
        item.setText(_translate("MainWindow", "cognitive load"))
        item = self.cur_report_display_table.verticalHeaderItem(7)
        item.setText(_translate("MainWindow", "physical activity"))
        item = self.cur_report_display_table.verticalHeaderItem(8)
        item.setText(_translate("MainWindow", "t-value"))
        item = self.cur_report_display_table.verticalHeaderItem(9)
        item.setText(_translate("MainWindow", "critical  t-value"))
        item = self.cur_report_display_table.verticalHeaderItem(10)
        item.setText(_translate("MainWindow", "accuracy"))
        item = self.cur_report_display_table.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "value"))
        __sortingEnabled = self.cur_report_display_table.isSortingEnabled()
        self.cur_report_display_table.setSortingEnabled(False)
        item = self.cur_report_display_table.item(0, 0)
        item.setText(_translate("MainWindow", "2.7"))
        item = self.cur_report_display_table.item(1, 0)
        item.setText(_translate("MainWindow", "2.9"))
        item = self.cur_report_display_table.item(2, 0)
        item.setText(_translate("MainWindow", "3.4"))
        item = self.cur_report_display_table.item(3, 0)
        item.setText(_translate("MainWindow", "4.2"))
        item = self.cur_report_display_table.item(4, 0)
        item.setText(_translate("MainWindow", "4.4"))
        item = self.cur_report_display_table.item(5, 0)
        item.setText(_translate("MainWindow", "(5,6,7,8)"))
        item = self.cur_report_display_table.item(6, 0)
        item.setText(_translate("MainWindow", "-0.2"))
        item = self.cur_report_display_table.item(7, 0)
        item.setText(_translate("MainWindow", "-0.4"))
        item = self.cur_report_display_table.item(8, 0)
        item.setText(_translate("MainWindow", "1.12"))
        item = self.cur_report_display_table.item(9, 0)
        item.setText(_translate("MainWindow", "1.74"))
        item = self.cur_report_display_table.item(10, 0)
        item.setText(_translate("MainWindow", "12"))
        self.cur_report_display_table.setSortingEnabled(__sortingEnabled)


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

