# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'CreateDataModelScreen.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets
from data_model import DataModel
from param import parms

class Ui_MainWindow(object):
    dm_path = "./Data/DataModel/" 
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(477, 476)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout.setContentsMargins(-1, -1, 0, -1)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.model_name_lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.model_name_lineEdit.setObjectName("model_name_lineEdit")
        self.horizontalLayout.addWidget(self.model_name_lineEdit)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.horizontalLayout_2.setSpacing(6)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_2.addWidget(self.label_3)
        self.num_of_days_lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.num_of_days_lineEdit.setObjectName("num_of_days_lineEdit")
        self.horizontalLayout_2.addWidget(self.num_of_days_lineEdit)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.choose_parmeter_table = QtWidgets.QTableWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.choose_parmeter_table.sizePolicy().hasHeightForWidth())
        self.choose_parmeter_table.setSizePolicy(sizePolicy)
        self.choose_parmeter_table.setObjectName("choose_parmeter_table")
        self.choose_parmeter_table.setColumnCount(2)
        self.choose_parmeter_table.setRowCount(4)
        item = QtWidgets.QTableWidgetItem()
        self.choose_parmeter_table.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.choose_parmeter_table.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.choose_parmeter_table.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.choose_parmeter_table.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.choose_parmeter_table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.choose_parmeter_table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.choose_parmeter_table.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.choose_parmeter_table.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.choose_parmeter_table.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.choose_parmeter_table.setItem(1, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.choose_parmeter_table.setItem(2, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.choose_parmeter_table.setItem(3, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.choose_parmeter_table.setItem(3, 1, item)
        self.verticalLayout_2.addWidget(self.choose_parmeter_table)
        self.save_model_btn = QtWidgets.QPushButton(self.centralwidget, clicked = self.save_mode_to_json)
        self.save_model_btn.setObjectName("save_model_btn")
        self.verticalLayout_2.addWidget(self.save_model_btn)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_3.addWidget(self.label_4)
        self.choose_model_to_form_comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.choose_model_to_form_comboBox.setObjectName("choose_model_to_form_comboBox")
        # Set choose_model_to_form_comboBox with Data models
        self.choose_model_to_form_comboBox.addItems(DataModel.lDataModels_names())
        self.horizontalLayout_3.addWidget(self.choose_model_to_form_comboBox)
        self.generate_form_btn = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.generate_form_btn.sizePolicy().hasHeightForWidth())
        self.generate_form_btn.setSizePolicy(sizePolicy)
        self.generate_form_btn.setObjectName("generate_form_btn")
        self.horizontalLayout_3.addWidget(self.generate_form_btn)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Create new data model:"))
        self.label_2.setText(_translate("MainWindow", "model name"))
        self.model_name_lineEdit.setText(_translate("MainWindow", "sleep analysis 3"))
        self.label_3.setText(_translate("MainWindow", "number of days"))
        self.num_of_days_lineEdit.setText(_translate("MainWindow", "14"))
        item = self.choose_parmeter_table.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "cognitive load"))
        item = self.choose_parmeter_table.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "amount of sleep"))
        item = self.choose_parmeter_table.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", "water consumption"))
        item = self.choose_parmeter_table.verticalHeaderItem(3)
        item.setText(_translate("MainWindow", "physical activity"))
        item = self.choose_parmeter_table.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "unit"))
        item = self.choose_parmeter_table.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "status"))
        __sortingEnabled = self.choose_parmeter_table.isSortingEnabled()
        self.choose_parmeter_table.setSortingEnabled(False)
        item = self.choose_parmeter_table.item(0, 0)
        item.setText(_translate("MainWindow", "interval"))
        item = self.choose_parmeter_table.item(0, 1)
        item.setText(_translate("MainWindow", "basic"))
        item = self.choose_parmeter_table.item(1, 0)
        item.setText(_translate("MainWindow", "double"))
        item = self.choose_parmeter_table.item(1, 1)
        item.setText(_translate("MainWindow", "derived"))
        item = self.choose_parmeter_table.item(2, 0)
        item.setText(_translate("MainWindow", "double"))
        item = self.choose_parmeter_table.item(3, 0)
        item.setText(_translate("MainWindow", "integer"))
        item = self.choose_parmeter_table.item(3, 1)
        item.setText(_translate("MainWindow", "basic"))
        self.choose_parmeter_table.setSortingEnabled(__sortingEnabled)
        self.save_model_btn.setText(_translate("MainWindow", "save model"))
        self.label_4.setText(_translate("MainWindow", "model name"))
        #self.choose_model_to_form_comboBox.setItemText(0, _translate("MainWindow", "sleep analysis 1"))
        self.generate_form_btn.setText(_translate("MainWindow", "generate form"))

# devloper define stuff
    def save_mode_to_json(self):
        lbasic = []
        # TODO: exception handling like single basic
        for i in range(self.choose_parmeter_table.rowCount()):
            if self.choose_parmeter_table.item(i, 1) is not None:
                if self.choose_parmeter_table.item(i, 1).text() == 'basic':
                    lbasic.append(parms[self.choose_parmeter_table.verticalHeaderItem(i).text()])
                if self.choose_parmeter_table.item(i, 1).text() == 'derived':
                    derived = parms[self.choose_parmeter_table.verticalHeaderItem(i).text()]

                
        dm = DataModel(self.model_name_lineEdit.text(), derived, lbasic,14)
        # TODO: implment taking from UI the dm
        dm.save_to_json()


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

