# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'DeveloperScreen.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(477, 476)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout.setContentsMargins(-1, -1, 0, -1)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.choose_alg_comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.choose_alg_comboBox.setObjectName("choose_alg_comboBox")
        self.choose_alg_comboBox.addItem("")
        self.horizontalLayout.addWidget(self.choose_alg_comboBox)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.cur_filter_setting_table = QtWidgets.QTableWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cur_filter_setting_table.sizePolicy().hasHeightForWidth())
        self.cur_filter_setting_table.setSizePolicy(sizePolicy)
        self.cur_filter_setting_table.setObjectName("cur_filter_setting_table")
        self.cur_filter_setting_table.setColumnCount(2)
        self.cur_filter_setting_table.setRowCount(5)
        item = QtWidgets.QTableWidgetItem()
        self.cur_filter_setting_table.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.cur_filter_setting_table.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.cur_filter_setting_table.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.cur_filter_setting_table.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.cur_filter_setting_table.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.cur_filter_setting_table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.cur_filter_setting_table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.cur_filter_setting_table.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.cur_filter_setting_table.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.cur_filter_setting_table.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.cur_filter_setting_table.setItem(1, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.cur_filter_setting_table.setItem(2, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.cur_filter_setting_table.setItem(2, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.cur_filter_setting_table.setItem(3, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.cur_filter_setting_table.setItem(3, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.cur_filter_setting_table.setItem(4, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.cur_filter_setting_table.setItem(4, 1, item)
        self.verticalLayout_2.addWidget(self.cur_filter_setting_table)
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout_2.addWidget(self.pushButton)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_2.addWidget(self.label_3)
        self.choose_report_comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.choose_report_comboBox.setObjectName("choose_report_comboBox")
        self.choose_report_comboBox.addItem("")
        self.horizontalLayout_2.addWidget(self.choose_report_comboBox)
        self.show_full_report_btn = QtWidgets.QPushButton(self.centralwidget)
        self.show_full_report_btn.setObjectName("show_full_report_btn")
        self.horizontalLayout_2.addWidget(self.show_full_report_btn)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Developer screen:"))
        self.label_2.setText(_translate("MainWindow", "algorithm"))
        self.choose_alg_comboBox.setItemText(0, _translate("MainWindow", "least squares + spearman correlation"))
        item = self.cur_filter_setting_table.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "cognitive load"))
        item = self.cur_filter_setting_table.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "amount of sleep"))
        item = self.cur_filter_setting_table.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", "water consumption"))
        item = self.cur_filter_setting_table.verticalHeaderItem(3)
        item.setText(_translate("MainWindow", "physical activity"))
        item = self.cur_filter_setting_table.verticalHeaderItem(4)
        item.setText(_translate("MainWindow", "time socializing"))
        item = self.cur_filter_setting_table.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "unit"))
        item = self.cur_filter_setting_table.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "filter"))
        __sortingEnabled = self.cur_filter_setting_table.isSortingEnabled()
        self.cur_filter_setting_table.setSortingEnabled(False)
        item = self.cur_filter_setting_table.item(0, 0)
        item.setText(_translate("MainWindow", "interval"))
        item = self.cur_filter_setting_table.item(0, 1)
        item.setText(_translate("MainWindow", "sum of 3 days"))
        item = self.cur_filter_setting_table.item(1, 0)
        item.setText(_translate("MainWindow", "double"))
        item = self.cur_filter_setting_table.item(1, 1)
        item.setText(_translate("MainWindow", "min. of 4 days"))
        item = self.cur_filter_setting_table.item(2, 0)
        item.setText(_translate("MainWindow", "double"))
        item = self.cur_filter_setting_table.item(2, 1)
        item.setText(_translate("MainWindow", "avg. of 2 days"))
        item = self.cur_filter_setting_table.item(3, 0)
        item.setText(_translate("MainWindow", "integer"))
        item = self.cur_filter_setting_table.item(3, 1)
        item.setText(_translate("MainWindow", "avg. of 3 days"))
        item = self.cur_filter_setting_table.item(4, 0)
        item.setText(_translate("MainWindow", "integer"))
        item = self.cur_filter_setting_table.item(4, 1)
        item.setText(_translate("MainWindow", "no filter"))
        self.cur_filter_setting_table.setSortingEnabled(__sortingEnabled)
        self.pushButton.setText(_translate("MainWindow", "update system configuration"))
        self.label_3.setText(_translate("MainWindow", "choose report:"))
        self.choose_report_comboBox.setItemText(0, _translate("MainWindow", "sleep analysis 1"))
        self.show_full_report_btn.setText(_translate("MainWindow", "show full report"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

